### ISSUE TITLE
Scheme not working, all black and white

### ISSUE THREAD

**Issue by ner0-m** [romgrk/doom-one.vim#1]
Hi, I'm tried this color scheme and sadly all I get is grey and white. No highlighting at all. I'm still a quite new to the vim script stuff, so I'm not sure what is the problem. I just wanted to let you know, would love to try this theme.

If you need more info, just let me know.

**Comment by romgrk** [comment]
A few questions:
 - How did you install it?
 - What is the output when you run `colorscheme doom-one`?
 - What vim/neovim version are you running on?

**Comment by ner0-m** [comment]
- I installed it via Plug `Plug 'romgrk/doom-one.vim'`
- I can see no output
- I'm running neovim master, with a version of a couple of days ago, quite recent

An here a screenshot of how it looks for me, after running `colorscheme doom-one`

![Screenshot_20201025_112242](https://user-images.githubusercontent.com/8257844/97104515-b5813400-16b4-11eb-9557-cad45bb79287.png)

**Comment by romgrk** [comment]
Just to be sure, you do have `syntax enable` and `filetype on`? And what happens if you do `:source ~/.config/nvim/bundle/doom-one.vim/colors/doom-one.vim`?

Edit: and btw if you're looking for a tabs bar plugin I've written [this one](https://github.com/romgrk/barbar.nvim) recently.

**Comment by ner0-m** [comment]
Yes to both. I tried it again with these options enabled again specifically, but still the same result. Same with sourcing the file directly.

Yes, I tried barbar (just the lines above). I'll give it a more serious try the next couple of days. I just wanted to remove all the plugins, to see if any mess with the color scheme.

EDIT: grammer

**Comment by romgrk** [comment]
That is mystifying. But other colorschemes work? So let's try this.

Open the doom-one.vim file, and run this: `:%g/^$/s:^:\='echom ' . line('.')`
Then run `:source %`, and tell me which line numbers you see. If you don't have time to see and it disappears, you can find them again in `:messages`.

**Comment by ner0-m** [comment]
At least the buildin neovim ones work.

<details>

<summary> The message output rather long </summary>

```
2
6
8
38
41
52
66
75
82
83
86
88
92
98
104
107
14
24
14
24
14
24
14
24
14
24
113
14
24
14
24
116
14
24
14
24
14
24
14
24
121
14
24
14
24
14
24
14
24
126
14
24
14
24
129
14
24
14
24
14
24
134
135
14
24
14
24
138
14
24
140
14
24
14
24
14
24
14
24
145
14
24
14
24
148
14
24
14
24
14
24
14
24
14
24
154
158
162
14
24
14
24
14
24
166
14
24
14
24
14
24
170
14
24
14
24
14
24
174
14
24
14
24
14
24
178
14
24
180
193
196
199
14
24
14
24
14
24
203
14
24
14
24
14
24
14
24
14
24
209
210
14
24
14
24
213
14
24
215
14
24
14
24
14
24
14
24
220
14
24
222
224
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
14
24
239
241
243
251
252
255
14
24
14
24
14
24
260
14
24
14
24
14
24
268
14
24
14
24
14
24
14
24
14
24
14
24
275
14
24
14
24
14
24
14
24
280
14
24
282
14
24
284
14
24
14
24
14
24
14
24
289
14
24
14
24
14
24
293
14
24
14
24
296
14
24
298
299
14
24
14
24
302
303
14
24
14
24
14
24
307
14
24
14
24
310
14
24
14
24
14
24
14
24
315
14
24
14
24
318
319
14
24
14
24
14
24
14
24
14
24
325
14
24
14
24
14
24
14
24
330
333
14
24
14
24
336
341
14
24
14
24
14
24
14
24
346
14
24
14
24
14
24
350
14
24
14
24
14
24
354
14
24
14
24
14
24
358
360
365
370
371
374
14
24
14
24
377
379
14
24
381
387
389
391
393
395
397
408
410
412
414
419
425
429
432
436
437
439
445
447
449
451
453
460
462
472
474
```

</details>

Does it help you in any way?

EDIT: My english today is really bad :D

**Comment by romgrk** [comment]
Not, your output is the same output I get, which means that the colorscheme ran without problem.

What is the output of `:hi Function`?

**Comment by ner0-m** [comment]
Weird.

Output: `Function       xxx guifg=#ECBE7B`, which seems correct. Tried it for a couple of other groups and all seem to be set correctly, but not rendered correctly.

**Comment by ner0-m** [comment]
Ah it seems I need to `set termguicolors`, then it looks correct. Thanks for all the walk through! Now I can try barbar :+1:

**Comment by romgrk** [comment]
LOL that took some time. Yes I also always forget about termguicolors. Good then.

**Comment by kmarzic** [comment]
Hi,

I am using VIm 8.2 and Nvim v0.5.1, and have the same problem (seeing gray and white colors).
I am using the following config:
```
Plug 'romgrk/doom-one.vim'
set t_Co=256
set background=dark
syntax on
colorscheme doom-one
```
Command `set termguicolors` is not helping.
Can you, please, give hints how to resolve this problem.

**Comment by romgrk** [comment]
Is that all your config? Are you using vim-plug? Do you have the proper `call plug#begin($vim . '/bundle')` and `call plug#end()` calls?

**Comment by kmarzic** [comment]
Hi,
Thanks for helping.
My test `.vimrc` is here:

```
kmarzic@dle5570:~ $ cat .vimrc
" vimrc
call plug#begin('~/.vim/plugged')
Plug 'chriskempson/base16-vim'
Plug 'romgrk/doom-one.vim'
call plug#end()
filetype on
set t_Co=256
set background=dark
" set background=light
syntax on
colorscheme doom-one
" colorscheme base16-apathy
"" eof
kmarzic@dle5570:~ $
```

- screenshot with the following .vimrc settigns:
```
set background=light
colorscheme base16-apathy
```

![screenshot_20220109 175633](https://user-images.githubusercontent.com/4183537/148692462-75e982c8-9b1f-4201-a18c-475752e8868f.png)

- screenshot with the following .vimrc settings:
```
set background=dark
colorscheme doom-one
```

![screenshot_20220109 175710](https://user-images.githubusercontent.com/4183537/148692530-0f2f001e-4947-4825-a9ef-d71928fc708e.png)

**Comment by romgrk** [comment]
Maybe https://stackoverflow.com/questions/62702766/termguicolors-in-vim-makes-everything-black-and-white ? Not sure about `termguicolors` behavior in vim, I only use neovim.

**Comment by kmarzic** [comment]
Hi,
Thanks!
I finally made it to work.
I added 3 additional options in .vimrc:

```
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
```

Complete minimal .vimrc is:
```
kmarzic@dle5570:~ $ cat .vimrc
" vimrc
call plug#begin('~/.vim/plugged')
Plug 'chriskempson/base16-vim'
Plug 'romgrk/doom-one.vim'
call plug#end()
filetype on
set t_Co=256
set background=dark
" set background=light
syntax on
colorscheme doom-one
" colorscheme base16-apathy
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
"" eof
kmarzic@dle5570:~ $
```
