### ISSUE TITLE
Too much purple

### ISSUE THREAD

**Issue by ahmedkhalf** [romgrk/doom-one.vim#12]
I recently switched to Treesitter, and honestly I am shocked. The colorscheme I grew to love is now just purple and yellow. I mean at this point might as well just change my terminal text color to purple and not use a colorscheme at all.

![image](https://user-images.githubusercontent.com/36672196/116216442-acebe200-a759-11eb-9f7e-1d61d6bdfe70.png)

Polyglot left, and Treesitter right ^

![image](https://user-images.githubusercontent.com/36672196/116216609-d99ff980-a759-11eb-85ca-6971c4c8d220.png)

Treesittter ^

**Comment by romgrk** [comment]
Yes, that's common with TS syntax highlight. I don't use golang so I've not adjusted doom-one for it but you can check which HL group they're using for variables with `:TSHigh<tab>`. You can then check if the group can be linked to something else without wreaking too much havoc. If so, you can propose the change here. If not, you need to ask the golang TS grammar to change their HL group to something reasonable.

**Comment by ahmedkhalf** [comment]
> You can then check if the group can be linked to something else without wreaking too much havoc.

How? Is there a command to check all of the things a highligh group affects in a buffer? or will I have to hover my cursor over everything and use `:TSHighlightCapturesUnderCursor`

**Comment by romgrk** [comment]
Change it and check a few common filetypes see if it's still looking good.

**Comment by romgrk** [comment]
Try `hi! link TSVariable Normal`, does it look better for you?
