### ISSUE TITLE
Too much purple in python files highlighting.

### ISSUE THREAD

**Issue by smit2909** [romgrk/doom-one.vim#16]
![Screenshot from 2021-06-24 15-02-09](https://user-images.githubusercontent.com/79797111/123239647-34a56100-d4fd-11eb-9510-b91c8f64112d.png)

- Almost everything other than strings is purple. I am using latest neovim with tree sitter

**Comment by romgrk** [comment]
```vim
hi! link TSVariable Normal
hi! link TSField Normal
```

Looks better that way?

**Comment by smit2909** [comment]
> ```viml
> hi! link TSVariable Normal
> hi! link TSField Normal
> ```
> 
> Looks better that way?

Yes..adding these lines works!

**Comment by romgrk** [comment]
Ok, not sure if that should be the default for all languages. I'll add it to my local config and if I'm happy with the results in a few days I'll commit it.

**Comment by romgrk** [comment]
I've updated the colorscheme.
