### ISSUE TITLE
Italic comments

### ISSUE THREAD

**Issue by Shatur** [romgrk/doom-one.vim#3]
Is it possible to display comments in _italic_ like in other one-like themes?

**Comment by romgrk** [comment]
Italic comments are an abomination of nature and should be destroyed like the pure evil they are.

I'll close this as I (evidently) won't add that, but if you'd like you can add the following line to your vimrc to enable the thing:

```vim
autocmd ColorScheme doom-one highlight Comment gui=italic
```
