### ISSUE TITLE
`set colorcolumn=81` is not working in this doom-one.vim

### ISSUE THREAD

**Issue by Adnios** [romgrk/doom-one.vim#7]
`set colorcolumn=81` is not working in this doom-one.vim

![image](https://user-images.githubusercontent.com/41060790/104866646-0766ec80-597a-11eb-91a4-73a217e0b54b.png)
![image](https://user-images.githubusercontent.com/41060790/104866666-1483db80-597a-11eb-806e-362430b01d7f.png)

**Comment by Adnios** [comment]
I can set `highlight ColorColumn guibg=Black` to make more obvious.
![image](https://user-images.githubusercontent.com/41060790/104867193-4ba6bc80-597b-11eb-9e54-0da257027250.png)

**Comment by romgrk** [comment]
Sorry for the delay, I've updated the color.
