### ISSUE TITLE
White tilde...

### ISSUE THREAD

**Issue by ahmedkhalf** [romgrk/doom-one.vim#8]
![image](https://user-images.githubusercontent.com/36672196/106385527-305f9680-63ea-11eb-81e3-6d04c79d2ad2.png)
I don't like the white tilde, can you please change the color to the gray used for inactive line number. If no, then could you please give me an indication as to how I can do this myself. Thanks in advance.

**Comment by ahmedkhalf** [comment]
I just noticed that in your screenshot there are no tildes, could you please tell me how you did that?

**Comment by ahmedkhalf** [comment]
I tried hiding the tildes using `highlight! EndOfBuffer ctermbg=bg ctermfg=bg guibg=bg guifg=bg` but I get: `E420: BG color unknown.` I also tried setting them to none, but they don't give any result/feedback, so it doesn't seem it affect anything.

**Comment by ahmedkhalf** [comment]
Okay fixed it, I had to remove the exclamation sign after highlight: `highlight EndOfBuffer guifg=bg`. It would be great if this is added as the default behavior though @romgrk

**Comment by romgrk** [comment]
Sorry for the delay.

That's weird it's defined here: https://github.com/romgrk/doom-one.vim/blob/master/colors/doom-one.vim#L120
Not sure why it's not working but running `verbose hi EndOfBuffer` would give me more info.

**Comment by ahmedkhalf** [comment]
@romgrk 
```
:verbose hi EndOfBuffer
EndOfBuffer    xxx guifg=#bbc2cf guibg=#282c34
        Last set from ~/.config/nvim/plugged/doom-one.vim/colors/doom-one.vim line 42
```
I use neovim nightly.

**Comment by ahmedkhalf** [comment]
Maybe the line should be changed from:
```call s:_('EndOfBuffer',       s:fg,           s:bg)```
to
```call s:_('EndOfBuffer',       s:bg,           s:bg)```?

**Comment by romgrk** [comment]
Sure, done.
